### PR TITLE
EnhancedCraft v0.2.0-alpha

### PR DESCRIPTION
**Pull request by realspectr3x**
## v0.2.0-alpha

This minor alpha update brings some new features, bug fixes, and changes to the mod.

### Changes

    - Bronze Tools, Ore, Gear.
        - 200 durability (for tools.)
        - Base durability multiplier of 12 (for armor.)
        - Enchantability of 17. (Better than everything in vanilla except for gold.)
        - Budget Iron.
        - Bronze Ore spawns anywhere from y-level 0 to 60 in veins of up to 15, 22 times per chunks.
        - Bronze Sword: Deals 5.5 damage with 1.6 swing speed. Slightly weaker than Iron, but better than Stone.
        - Bronze Pickaxe: 5f Pickaxe Multiplier. Deals 3.5 damage with 1.2 swing speed. Mining level of 2. Slightly worse than Iron, but better than Stone.
        - Bronze Axe: 5f Axe Multiplier. Deals 7.5 damage with 1.0 swing speed. Slightly worse than Iron, but better than Stone.
        - Bronze Shovel: 5f Shovel Multiplier. Deals 3.5 damage with 1.1 swing speed. Slightly worse than Iron, but better than Stone.
        - Bronze Hoe: 5f Hoe Multiplier.  Deals 1 damage with 2.5 swing speed. Slightly worse than Iron, but better than Stone.
        - Bronze Set: {1, 5, 5, 2} Leggings as strong as iron, otherwise the same as chain.

    - Etherium Ore changes.
        - Now spawns from y-level 6 to y-level 9, from veins of up to 2.

### CODE REVIEW

**Comment by WivioPooCode** [comment]
Im going to load up the mod in a few minutes

**Comment by WivioPooCode** [comment]
The etherium items show their code name
[https://imgur.com/a/ajlbolG](https://imgur.com/a/ajlbolG)

**Comment by realspectr3x** [comment]
@WivioPooCode I have fixed the Etherium lang files.

**Review by Ryn-git — APPROVED** [review]

**Review by WivioPooCode — APPROVED** [review]
Pog

**Comment by realspectr3x** [comment]
pog yes @WivioPooCode

**Pull request merged**
